const questions = [
  {
    id: 1,
    number: 1,
    subject: "Geography",
    difficulty: "Easy",
    marks: 2,
    question: "Which of the following is the longest river in India?",
    options: [
      { text: "Ganga", correct: true },
      { text: "Yamuna", correct: false },
      { text: "Godavari", correct: false },
      { text: "Narmada", correct: false },
    ],
    userAnswer: "Ganga",
    userAnswerCorrect: true,
    explanation:
      "The Ganga is the longest river in India, flowing for approximately 2,525 kilometers from the Gangotri glacier to the Bay of Bengal.",
  },
  {
    id: 2,
    number: 2,
    subject: "History",
    difficulty: "Easy",
    marks: 2,
    question: "In which year did India gain independence?",
    options: [
      { text: "1947", correct: true },
      { text: "1950", correct: false },
      { text: "1935", correct: false },
      { text: "1919", correct: false },
    ],
    userAnswer: "1947",
    userAnswerCorrect: true,
    explanation: "India gained independence in 1947.",
  },
  {
    id: 3,
    number: 3,
    subject: "Polity",
    difficulty: "Easy",
    marks: 2,
    question: "Which Article in the Indian Constitution guarantees equality before the law?",
    options: [
      { text: "Article 14", correct: true },
      { text: "Article 19", correct: false },
      { text: "Article 21", correct: false },
      { text: "Article 32", correct: false },
    ],
    userAnswer: "Article 21",
    userAnswerCorrect: false,
    explanation: "Article 14 of the Indian Constitution guarantees equality before the law and equal protection of the laws to all persons within the territory of India.",
  },
  {
    id: 4,
    number: 4,
    subject: "Indian Economy",
    difficulty: "Medium",
    marks: 2,
    question: "Which institution is primarily responsible for framing monetary policy in India?",
    options: [
      { text: "Reserve Bank of India (RBI)", correct: true },
      { text: "Securities and Exchange Board of India (SEBI)", correct: false },
      { text: "Ministry of Finance", correct: false },
      { text: "NITI Aayog", correct: false },
    ],
    userAnswer: "Reserve Bank of India (RBI)",
    userAnswerCorrect: true,
    explanation: "The Reserve Bank of India (RBI) is the central bank and is primarily responsible for monetary policy in India, including tools like repo rate and open market operations.",
  },
  {
    id: 5,
    number: 5,
    subject: "Environment",
    difficulty: "Easy",
    marks: 2,
    question: "Which greenhouse gas is the largest contributor to anthropogenic global warming?",
    options: [
      { text: "Carbon Dioxide (CO2)", correct: true },
      { text: "Methane (CH4)", correct: false },
      { text: "Nitrous Oxide (N2O)", correct: false },
      { text: "Ozone (O3)", correct: false },
    ],
    userAnswer: "Methane (CH4)",
    userAnswerCorrect: false,
    explanation: "Carbon dioxide (CO2) is the largest contributor to anthropogenic climate change due to its high volume of emissions from fossil fuel combustion and long atmospheric lifetime.",
  },
];

export default questions;
